export const FETCH_USER = "FETCH_USER";

export const FETCH_CONFIG = "FETCH_CONFIG";
export const SELECT_CONFIG = "SELECT_CONFIG";

export const FETCH_SURVEYS = "FETCH_SURVEYS";
export const FETCH_SURVEYS_PENDING = "FETCH_SURVEYS_PENDING";
export const FETCH_SURVEYS_REJECTED = "FETCH_SURVEYS_REJECTED";
export const FETCH_SURVEYS_FULFILLED = "FETCH_SURVEYS_FULFILLED";

export const FETCH_CONFIG_PENDING = "FETCH_CONFIG_PENDING";
export const FETCH_CONFIG_REJECTED = "FETCH_CONFIG_REJECTED";
export const FETCH_CONFIG_FULFILLED = "FETCH_CONFIG_FULFILLED";